version: '2'

services:
    masternode:
        image: kunstmaan/master-multichain
        ports:
            - "7447:7447"
            - "8000:8000"
        environment:
            VIRTUAL_HOST: mulichain-master.docker
            VIRTUAL_PORT: 8000
    explorer:
        image: kunstmaan/explorer-multichain
        depends_on:
            - masternode
        ports:
            - "2750:2750"
        environment:
            VIRTUAL_HOST: multichain-explorer.docker
            VIRTUAL_PORT: 2750
        links:
            - masternode
        stdin_open: true
        tty: true
    slavenode1:
        image: kunstmaan/node-multichain
        depends_on:
            - masternode
        links:
            - masternode
    slavenode2:
        image: kunstmaan/node-multichain
        depends_on:
            - masternode
        links:
            - masternode
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            VIRTUAL_HOST: multichain-mysql.docker
            VIRTUAL_PORT: 3306
            MYSQL_ROOT_PASSWORD: r00t
            MYSQL_DATABASE: blockchain
            MYSQL_USER: blockchain
            MYSQL_PASSWORD: blockchain
