version: '2'

services:
    masternode:
        image: kunstmaan/master-multichain
        stdin_open: true
        tty: true
        ports:
            - "7447:7447"
            - "8000:8000"
        expose:
            - 7447
            - 8000
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7447
            RPC_PORT: 8000
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            PARAM_ANYONE_CAN_RECEIVE: anyone-can-receive|true
            PARAM_ANYONE_CAN_SEND: anyone-can-send|true
            PARAM_ANYONE_CAN_ISSUE: anyone-can-issue|true
            PARAM_ANYONE_CAN_CONNECT: anyone-can-connect|true
            PARAM_ANYONE_CAN_MINE: anyone-can-mine|true
    slavenode:
        image: kunstmaan/node-multichain
        stdin_open: true
        tty: true
        expose:
            - 7447
            - 8000
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7447
            RPC_PORT: 8000
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MASTER_NODE: masternode
        links:
            - masternode
    explorernode:
        image: kunstmaan/explorer-multichain
        stdin_open: true
        tty: true
        expose:
            - 2750
            - 7447
            - 8000
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7447
            RPC_PORT: 8000
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MASTER_NODE: masternode
        links:
            - masternode
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            VIRTUAL_HOST: multichain-mysql.docker
            VIRTUAL_PORT: 3306
            MYSQL_ROOT_PASSWORD: r00t
            MYSQL_DATABASE: blockchain
            MYSQL_USER: blockchain
            MYSQL_PASSWORD: blockchain
